# -*- coding: utf-8 -*-
"""vgFinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3RfEpaeSaqLRW9xIdmobRqT4-KdTFmd
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive

cd /content/drive/MyDrive/123/powerful-gnns

!python3 main.py --dataset combinevg1 --filename modelvg1,5 --epoch 400  --final_dropout 0 --batch_size 64