# -*- coding: utf-8 -*-
"""QG24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/125HAT8O72YdCrzHA8XMORKI93DKJdsvS
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive

cd /content/drive/MyDrive/123/powerful-gnns

!python3 main.py --dataset combineqg23 --filename modelqg23,2 --batch_size 64  --num_layers 8

!python3 main.py --dataset combineqg23 --filename modelqg23,9 --epoch 450  --num_layers 8

!python3 main.py --dataset combinehg2 --filename modelhg2,7 --epoch 400 --final_dropout 0  --num_layers 8 --batch_size 128

!python3 main.py --dataset combinehg2 --filename modelhg2,10 --epoch 400  --num_layers 8 --batch_size 128

!python3 main.py --dataset combinehg2 --filename modelhg2,6 --epoch 400 --batch_size 64

